### ISSUE TITLE
Armar procesamiento de tablas ETI desde base en server

### ISSUE THREAD

**Issue by pablotis** [d4t4tur/turismo_naturaleza#5]
# Tablas a migrar en R para la ETI.

- Para el último año disponible se podría dejar 2019, diría de replicar y luego ver si podemos incorporar alguna comparación o incluso sacar un informe anual por cada año, viendo si todos los cuadros valen de cara a las restricciones de ingreso al país en años 2020 y 2021.

- [ ] Tabla 1:
![imagen](https://user-images.githubusercontent.com/30708601/157717909-a2785428-bb22-4152-88e2-9b75c69277a8.png)

- [ ] Tabla 2:
![imagen](https://user-images.githubusercontent.com/30708601/157717979-fce90225-4d31-491d-95f8-6e6b64fc8f0c.png)

- [ ] Tabla 3:
![imagen](https://user-images.githubusercontent.com/30708601/157718119-ac76d97f-f96d-45b4-b8fc-96cd8977fb32.png)

- [ ] Tabla 4:
![imagen](https://user-images.githubusercontent.com/30708601/157718190-3f138a6c-edad-47d2-8afa-778634942202.png)

- [ ] Tabla 5:
![imagen](https://user-images.githubusercontent.com/30708601/157718277-4f6169f8-f22a-44e3-bb1e-f5cf82f3e0d4.png)

cc @TuQmano @vickyciccia

**Comment by pablotis** [comment]
Probando asignar a Marian cc @mcippo

**Comment by pablotis** [comment]
Probando asignar a Marian cc @mcippo

**Comment by mcippo** [comment]
Perfecto, pensando en el armado de la base ETI para levantar desde R, la idea sería trabajar con info de 2019-2021?

**Comment by pablotis** [comment]
- Las series, si se puede, las haría con todos los años a partir de 2014.
- Las tablas con un año en particular, arrancaría con 2019, y luego con sólo cambiarle el año podemos armar un informe por año

¿cómo la ven?

**Comment by mcippo** [comment]
oks, entonces lo más complicado puede llegar a ser armar una base unificada de la eti (por el momento, trabajamos con bases anuales), porque cambian las preguntas y las actividades vinculadas a la naturaleza se fueron modificando entre 2014-2020. Pero se puede arreglar, hay que encontrarle la vuelta nomás.

**Comment by pablotis** [comment]
@mcippo esto ya lo tenemos cerrado, no? Digo, las tablas están armadas, sólo queda pasarlas al informe con `{gt}`? si es así, cerrate este issue y armemos otro para trabajar el informe específicamente.

**Comment by mcippo** [comment]
Oka, sí, las tablas están armadas, falta que pase el script al repo y hacer el trabajo con gt
