### ISSUE TITLE
renombrar scripts de procesamiento

### ISSUE THREAD

**Issue by pablotis** [d4t4tur/turismo_naturaleza#9]
Pasar de:

```
- armado_eti.R
- armado_evyth.R
- metadata_eti.R
- metadata_evyth.R 
```

a:

```
- eti_armado.R
- eti_metadata.R
- evyth_armado.R
- evyth_metadata.R
```

**Comment by SSoubie** [comment]
Done

**Comment by pablotis** [comment]
reabro hasta que impactemos los cambios en el repo. Vayamos con los pull request por las dudas

cc @Lei541

**Comment by Lei541** [comment]
Hola!! Perodn, Que sería lo que hay que hacer?

**Comment by pablotis** [comment]
Un detalle nomás de la estructura de la carpeta, pero decíamos de cambiar los nombres de los archivos como en el ejemplo en el cuerpo del issue (que acabo de actualizar para se más claro, je
